Portfolio webpage
HossainAraf/Portfolio pull request #1
Opened 2023-06-02 11:46 UTC by HossainAraf

This is a Microverse assignment. CSS flex property is reflected here.

2023-06-02 14:38 UTC, Kossi-stack requested changes
## Hi @HossainAraf,

**Good job so far! 👍🏻**
There are some issues that you still need to work on to go to the next project but you are almost there!💪

![68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966](https://user-images.githubusercontent.com/81444338/170121142-a9f93bb7-38bb-45cc-8327-aab2501ef90a.gif)

## To Highlight

✅ Linter error checks validated
✅ Documented your work professionally
✅ README file is descriptive.
✅ Commit messages are meaningful.

## Required Changes ♻️

 - [ ] Kindly add a descriptive pull request message, This helps other programmers who want to take a look at your code to understand what changes you made to a particular branch, you can find an example [here](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md#5-basic-rules-to-follow-in-microverse-projects).
 - [ ] Kindly make your social handle a link in the Readme file. Like the way issues is link.

 _Check the comments under the review for more changes_.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

_**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-06-02 14:38 UTC, Kossi-stack commented on index.html
> +    <div class="logo">
- [ ] Kindly make sure to use `a` tag
- This is for three reasons: convention, semantics, and user experience(UX). [Check this link](https://ux.stackexchange.com/questions/81727/why-is-it-standard-for-a-website-logo-to-navigate-to-the-home-page) for more info.

2023-06-02 14:38 UTC, Kossi-stack commented on index.html
> +      <h2>I'm Hossain. <br> Glad to see you!</h2>
- [ ] Kindly make sure to use the `h1` tag for the main title.
- Because If you want that google (and other search engines) to know about a specific topic, in this case, you, use an `h1` tag. [Check this link](https://www.reliablesoft.net/h1-tag/) for more info. If you want that google (and other search engines) to know about a specific topic, in this case, you, use an h1 tag. [Check this link](https://www.reliablesoft.net/h1-tag/) for more info.

2023-06-02 14:38 UTC, Kossi-stack commented on index.html
> +    <section class="my-description">
- [ ] Kindly make sure to use `p` tag.
-  This way will be semantically correct and the screen readers and other technologies will thank you

2023-06-02 17:37 UTC, Qoosim requested changes
#  *Status: Required Changes* :recycle: 

Hi @HossainAraf, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


## Highlights
-  No linter errors. :heavy_check_mark: 
-  Good README file. :heavy_check_mark: 
-  Correct GitHub Flow. :heavy_check_mark: 

![](https://camo.githubusercontent.com/38ce8c8b213b08e2d9bb85a0b79702ad512f3910f803ec3d7917b4e0110c9044/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f7741366159414f336a4836526d55494259732f67697068792e676966)

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-02 17:37 UTC, Qoosim commented on index.html
> +      <h1> <p>I'm Hossain. </p> <br> <p>Glad to see you!</p> </h1>
- [ ] There's no need for `p` tag inside the `h1` tag. It is fine like this. :point_down: 

```
  <h1>I'm Hossain. <br> Glad to see you!</h1>
```

2023-06-02 17:37 UTC, Qoosim commented on index.html
> +    </section>
- [ ] As requested by the previous reviewer, it is required to use `p` tag for this intro. Kindly do that.

2023-06-02 17:37 UTC, Qoosim commented on index.html
> +    </section>
- [OPTIONAL] You're not supposed to use many `sections` tag for this section. The headline is just a section that is supposed to use only one `section` tag. You can use generic div tag to and other applicable tags to divide the content of your headline section. Kindly readdress this.

2023-06-02 17:37 UTC, Qoosim commented on index.html
> +    </section>
- [OPTIONAL] The background image is just decoration image which is supposed to be added by the background-image property in css not with `img` tag . If an image is not part of the content (aesthetic reasons) use CSS background-image. [Check this link](https://stackoverflow.com/questions/492809/when-to-use-img-vs-css-background-image) for more info. I made this optional because it escaped the sight of the previous reviewer. Kindly readdress this, it is very important.

2023-06-03 12:22 UTC, AbdusSattar-70 approved these changes
### STATUS: APPROVE 🏆 
Hi @HossainAraf, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- PROFESSIONAL README
- FOLLOWING THE REVIEWER'S SUGGESTIONS
- CORRECT USE OF GITHUB WORKFLOWS 
![ThumbOkayGIF](https://github.com/HossainAraf/Portfolio/assets/118761303/1d743d56-1784-407a-b6cc-f60073909611)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-03 12:38 UTC, HossainAraf commented
Thanks
Best Regards
Md. Arafat Hossain

On Sat, 3 Jun 2023 at 13:22, Abdus Sattar ***@***.***> wrote:

> ***@***.**** approved this pull request.
> STATUS: APPROVE 🏆
>
> Hi @HossainAraf <https://github.com/HossainAraf>,
>
> Your project is complete! There is nothing else to say other than... it's
> time to merge it [image: :shipit:]
> Congratulations! 🎉
> Highlights
>
>    - PROFESSIONAL README
>    - FOLLOWING THE REVIEWER'S SUGGESTIONS
>    - CORRECT USE OF GITHUB WORKFLOWS
>    [image: ThumbOkayGIF]
>    <https://user-images.githubusercontent.com/118761303/243090691-1d743d56-1784-407a-b6cc-f60073909611.gif>
>
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix won't stop the approval of this
> PR. However, I strongly recommend you to take them into account as they can
> make your code better. Some of them were simply missed by the previous
> reviewer and addressing them will really improve your application.*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/HossainAraf/Portfolio/pull/1#pullrequestreview-1459283412>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A7A6IL4GC4W5NQAGUXTQUSDXJMT73ANCNFSM6AAAAAAYYGTRDU>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-06-03 12:40 UTC, merged